### ISSUE TITLE
two channel synchronous sampling

### ISSUE THREAD

**Issue by mzy2240** [mccdaq/daqhats#12]
I checked the document but did not find any doc related to the synchronous sampling in Python. Is it possible to do two channel synchronous sampling with just one MC118 board? What's the max possible sample rate for this situation? Thanks!!

**Comment by nwright-mcc** [comment]
Please contact MCC support at https://www.mccdaq.com/support/support_form.aspx for device or library usage questions.

The MCC 118 has a single ADC so cannot sample two channels simultaneously.  Multiple boards are required for simultaneous sampling.
