### ISSUE TITLE
hat_error_message is missing a case for undefined

### ISSUE THREAD

**Issue by jschank** [mccdaq/daqhats#16]
There is an error in the source code for the lib.

hat_error_message(RESULT_UNDEFINED), will return the error message for RESULT_COMMS_FAILURE
There is a mismatch between the strings in the HAT_ERROR_MESSAGE array.

The Fix is to add another Case in hat_error_message(int result), and to increment the index in the default case.

IMO it would be better to put the undefined error message, as its own string. (and not in the array) that way, in the future, a missed index would at least return the undefined message which is slightly less wrong than what it does now. :)

**Comment by nwright-mcc** [comment]
Thanks, I'll get this into the next release.

**Comment by nwright-mcc** [comment]
Fix is released.
