### ISSUE TITLE
Web server example Import Error

### ISSUE THREAD

**Issue by jacob-lapenna** [mccdaq/daqhats#2]
After `pip install dash dash-renderer dash-html-components dash-core-components` and running `$ ./web_server.py` or `$ python web_server.py` I get `ImportError: cannot import name Event` from `dash.dependencies`. After reading that the Event system was removed (see https://community.plot.ly/t/why-cant-i-import-the-event-dash-dependency/19288), I commented it out in the import statement and naturally got `NameError: name 'Event' is not defined` on line 389 of web_server.py with no import error. Potential guidance on a fix is detailed here: https://community.plot.ly/t/dash-events-button/19791/3?u=nedned

**Comment by nwright-mcc** [comment]
Thank you for the feedback, I have forwarded this to the web server example developer so we can incorporate the fix.

**Comment by nwright-mcc** [comment]
We have added instructions in the readme for the web server example on how to work around this issue.
