### ISSUE TITLE
install scripts use quirky -D option for older coreutils versions

### ISSUE THREAD

**Issue by RolfKal** [mccdaq/daqhats#21]
The various make files use the Linux install command to install the different files to the final locations. They use the -D option which is supposed to create intermediate directory levels in the destionation but can have some weird effects in older coreutils installations. It would be more compatible to first prepend the install command with an according

install -d $(INSTALL_DIR)

and then leave the -D option away from the following installation command. This makes the make scripts more compatible with different coreutils versions.

**Comment by nwright-mcc** [comment]
Fixed in 1.4.0.0.
