### ISSUE TITLE
mcc118 hangs on a_in_scan_start and then returns HatError -3

### ISSUE THREAD

**Issue by k3tj0w** [mccdaq/daqhats#28]
I guess this issue corresponds to already closed one #14
In our case, after taking ~100 samples, the program hanged at `<a_in_scan_start>` function. Once restarted it quits with `<daqhats.hats.HatError: Addr 0: Incorrect response -3.>` (also thrown by the `<a_in_scan_start>` function). 
Our python code is the following:

```python
def scan(hat, channels, actual_scan_rate, samples_per_channel, read_request_size, timeout):
    options = OptionFlags.DEFAULT
    channel_mask = chan_list_to_mask(channels)
    try:
        logger.info("Starting scan")
        hat.a_in_scan_start(channel_mask, samples_per_channel, actual_scan_rate, options)
        result = _read_data_numpy(hat, channels, samples_per_channel, read_request_size, timeout)
        return result
    except (HatError, ValueError) as err:
        logger.error("Error during scan", exc_info=err)
        raise err
    finally:
        logger.info("Scan finished - cleaning...")
        hat.a_in_scan_stop()
        hat.a_in_scan_cleanup()

def _read_data_numpy(hat, channels, samples_per_channel, read_request_size, timeout):
    num_channels = len(channels)
    total_samples_read = 0
    result = numpy.array([])
    while total_samples_read < samples_per_channel:
        try:
            read_result = hat.a_in_scan_read_numpy(read_request_size, timeout)
        except (HatError, ValueError):
            raise
        if read_result.hardware_overrun:
            logger.error("Hardware overrun")
            break
        elif read_result.buffer_overrun:
            logger.error("Buffer overrun")
            break

        samples_read_per_channel = int(len(read_result.data) / num_channels)
        total_samples_read += samples_read_per_channel
        result = numpy.append(result, read_result.data)
    return result
```
We are taking scan every 60 seconds on 7 channels (0, 1, 2, 3, 4, 5, 6) reading 512 samples for each of them (both `<actual_scan_rate>`, `<samples_per_channel>`, `<read_request_size>` are equal to 512). The problem occurred on one of our five devices after switching to the new Raspberry Pi 4 and updating the daqhat software to 1.4.0.0 (however, I do not expect this might my the reason). The other four devices are working fine. All setups come with exactly the same configuration and are running the same program. Our previous installation (with Raspberry Pi 3 and daqhat v 1.1.0.2) used to work reliably for almost 2 years.

**Comment by jeffreyg3** [comment]
As you had 4 out of 5 systems working, it is doubtful the problem is with the MCC 118.  I could not duplicate the issue, even with a RPi 4 and latest DaqHats rev.
