### ISSUE TITLE
Support Ubuntu Server 20.04 LTS for raspberry pi 4B+

### ISSUE THREAD

**Issue by MrXinWang** [mccdaq/daqhats#31]
Hi @nwright98 @nwright-mcc @jperreault-mcc @jsigren !

Recently in my spare time I have played with the MCC128 on Ubuntu Server 20.04 LTS for raspberry pi 4B+ and made the `daqhats` build on it. Also, the `data_logger` example builds and GUI can show up. Since current master branch have some linking and dependancy issues on Ubuntu 20.04, I've prepared a prototype https://github.com/MrXinWang/daqhats/tree/rasp_pi_4b_ubuntu_20_04 and hope to contribute this prototype to upstream here.

Since I am not sure if you accept PRs here, please feel free to review the code and pick the top 3 commits to the master branch. Thanks!

**Comment by jeffreyg3** [comment]
Hi,
The people you posted this request to do not monitor nor respond to posts.  
Thank you for your suggestions.  MCC Hats are made to function solely on Raspberry Pi / Raspbian.  At present there are no plans to make them work on any other platform nor OS.
Best regards,
Jeff
