### ISSUE TITLE
Issues when downloading with Docker

### ISSUE THREAD

**Issue by mbrierley01** [mccdaq/daqhats#45]
While trying to use daqhats inside of a Docker container I receive the error 'Error: module 'daqhats has no attribute 'mcc118''. This occurs on a Raspberry Pi 3B+.

**Comment by jeffreyg3** [comment]
Docker container is not supported (never tested)

**Comment by bearsh** [comment]
just for the record, daqhats works fine inside a docker container as long as the gpios, i2c and spi are available from inside the container...
