### ISSUE TITLE
 MCC172 examples C data_logger

### ISSUE THREAD

**Issue by andyhsieh1010** [mccdaq/daqhats#48]
I can execute the example C "logger".
I output "10Hz" "sine wave" through a signal generator.
I can't see the X-axis units.
But I can see "logger.c line179 freq_val value" in the console. I print it on the console.

Please tell me what I might be doing wrong.
Thank you

![image thumb png 40205df053bfd6cf7cc1f0ca1920f376](https://user-images.githubusercontent.com/54426479/201249558-29513883-49e1-4563-9db0-a12e1b0cceb8.png)

 freq_val value
![2022-11-11 102251](https://user-images.githubusercontent.com/54426479/201249581-32eee02e-31b7-4e80-b786-649ef54f2c3d.png)

**Comment by jeffreyg3** [comment]
![Screenshot from 2022-11-14 08-23-34](https://user-images.githubusercontent.com/35742455/201671848-41b8e6f7-5fd4-49ec-8870-4621d0d7a896.png)
I'm not seeing that on my Raspberry Pi 4.
My guess is you have something not installed or installed wrong for this example.
In particular that graph object, the GTKDatabox.
I recommend you uninstall your existing daqhats installation,  download and install a fresh copy of the daqhats software, review and run the instructions found in the readme.md found in the folder for that example.

**Comment by andyhsieh1010** [comment]
OK!
I reinstalled all programs.
When I install GTKDatabox.
This error occurs on the terminal.
But I can't solve it.
I would like to ask what is your environment?
I am using Pi3 Model B OS: Pi OS 64bit
![image](https://user-images.githubusercontent.com/54426479/202123162-8d6b6e1c-c78c-4ec0-9c00-3c78468671f7.png)

**Comment by jeffreyg3** [comment]
I've run this on RPi 3b 32 bit, and RPi 4B 32 and 64 bit.

**Comment by andyhsieh1010** [comment]
HI @jeffreyg3 
It's really a system environment problem.
I changed the board from 64bit to 32bit to solve this problem.
Thanks for your help
![mcc172_logger](https://user-images.githubusercontent.com/54426479/202363765-6d90d7e9-9c4c-4dbf-8322-1443c410f830.png)

**Comment by nwright-mcc** [comment]
This has been fixed for the 64-bit OS.
