### ISSUE TITLE
I can not save data to log file when using 2 mcc172 with 4 sensor

### ISSUE THREAD

**Issue by hanhg95** [mccdaq/daqhats#50]
I am using 2 mcc 172 and 4 pressure sensor. 
I can save the data of only 1 mcc 172 with 2 sensor. 
i want to save measurement data of 2 mcc172 and 4 sensor. I need help 
please guide me!

**Comment by jeffreyg3** [comment]
This was also posted on https://forum.digilent.com/topic/24527-how-to-measure-and-save-data-of-vibration-by-using-2-mcc172/
where it was answered.
