### ISSUE TITLE
Insallation issue

### ISSUE THREAD

**Issue by DrBwts** [mccdaq/daqhats#51]
I get as far as `sudo ./install.sh` 

which gives,

`sudo: ./install.sh: command not found`

so I used `sudo chmod a+x install.sh` to make sure `sudo` was seeing the script as executable & then ran `sudo ./install.sh` 

but this now give,

`sudo: unable to execute ./install.sh: No such file or directory`

then I tried `sudo install.sh`

which gives me,

`sudo: install.sh: command not found'

any ideas?

**Comment by nwright-mcc** [comment]
Make sure you are in the daqhats directory before running that command.  If you cloned daqhats into a different directory, cd into that directory then run the install command.

**Comment by DrBwts** [comment]
Hi I'm running from the `daqhats` directory

**Comment by nwright-mcc** [comment]
Can you please attach the output of running `ls` in your daqhats directory?
