### ISSUE TITLE
MCC152 dio_config_write_dict(item, value_dict) fails

### ISSUE THREAD

**Issue by SLongofono** [mccdaq/daqhats#55]
Calls to the configuration write with a dictionary fail with the following traceback: "TypeError: byref() argument must be a ctypes instance, not _ctypes.PyCSimpleType".
I have verified that I can set and access configuration on a per-bit basis successfully.

Steps to reproduce:
1. Instantiate a mcc152 type, ex. myHat = mcc152(0)
2. Prepare a dictionary for bulk configuration, ex myConfig=dict(zip( [0,1,2],[1,1,0]))
3. Call the function: myHat.dio_config_write_dict(DIOConfigItem.DIRECTION, myConfig)

Additional Information:
Platform: Debian 64-bit
Python: v3.9.2

**Comment by nwright-mcc** [comment]
This has been fixed in version 1.4.0.7.
