### ISSUE TITLE
Running program in Docker container can't get HAT devices.

### ISSUE THREAD

**Issue by Jianxin2021-CHN** [mccdaq/daqhats#56]
When I package the Python program and its dependencies into a Docker container and run the Docker container. Although it shows that "Successfully installed daqhats-1.4.0.6" and the package can be imported in Python3.9 successfully, the HAT devices can't be obtained.

I have tried to open the serial port permission to the Docker container, using the flag `--device /dev/ttyAMA0` and `--privileged`…… It's still not work and returns `Addr 0: Error: No HAT devices found`.

So is support for Docker added? Is there anything wrong with my operation? What should I do to realize the rapid deployment and transplantation of Python program based on `daqhats'?

Thank you very much!

**Comment by bearsh** [comment]
AFAIK daqhats don't communicate over a serial connection.

you need to make the i2c port, the spi port and some gpio available to the container...
