### ISSUE TITLE
MCC172 ID SD and ID SC not available to access EEPROM

### ISSUE THREAD

**Issue by bobg-zymbit** [mccdaq/daqhats#59]
We have a Raspberry PI CM4 I/O board that doesn't have ID SD (pin27) and ID SC (pin28) available on the 40 pin GPIO header. Is it possible there's another way we can access the MCC172 EEPROM information, perhaps directly through a file on the PI? Any workarounds you could recommend?

**Comment by nwright-mcc** [comment]
If there is no I2C bus connected to pins 27 and 28 then it is not possible to read the HAT EEPROM information on that CM4 I/O board.  

One workaround would be to set the HAT address to something other than 0 and connect the MCC 172 to a standard Raspberry Pi.  Install daqhats on that Pi, and it will read and store the EEPROM image in _/etc/mcc/hats/eeprom_X.bin_, where X is the HAT address.  This file could then be copied to the same location on the CM4 and daqhats would use it.  The MCC 172 would need to stay at the same address (or the filename changed), but it could not be at address 0.  The SPI bus would also have to be manually enabled in /boot/config.txt or through raspi-config.

There may be other options - can you share information on the I/O board?

**Comment by bobg-zymbit** [comment]
Thank you for getting back so quickly.That works and gives us a software workaround for now.

The I/O board is our own Zymbit board for use with our SCM security module Development Kits. ID_SD/ID_SC are wired up in the next revision of the board.
