### ISSUE TITLE
chan_string is too small line 214 in daqhats_utils.h

### ISSUE THREAD

**Issue by gpe92** [mccdaq/daqhats#60]
Hi,

I guess that chan_string is too small line 214 in daqhats_utils.h as it is reported during compilation:
`
./../daqhats_utils.h: In function ‘convert_chan_mask_to_string’:
../../daqhats_utils.h:225:35: warning: ‘%d’ directive writing between 1 and 10 bytes into a region of size 8 [-Wformat-overflow=]
  225 |             sprintf(chan_string, "%d, ", i);
      |                                   ^~
../../daqhats_utils.h:225:34: note: directive argument in the range [0, 2147483647]
  225 |             sprintf(chan_string, "%d, ", i);
      |                                  ^~~~~~
../../daqhats_utils.h:225:13: note: ‘sprintf’ output between 4 and 13 bytes into a destination of size 8
  225 |             sprintf(chan_string, "%d, ", i);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by nwright-mcc** [comment]
Thanks, the buffer size has been fixed.
