### ISSUE TITLE
Suggestion of improvements in doc/install

### ISSUE THREAD

**Issue by sciunto** [mccdaq/daqhats#65]
Hi,

To install the library on Rpi4B with raspbian, I had to install first :

```
sudo apt install libraspberrypi-dev raspberrypi-kernel-headers
```

I think that adding this tips in
https://mccdaq.github.io/daqhats/install.html
would be valuable.

Thanks!

**Comment by nwright-mcc** [comment]
Hello, the upcoming release to support the Pi 5 adds checks for required libraries to the install process so the user will not have to do it.

**Comment by sciunto** [comment]
awesome! thanks.
