### ISSUE TITLE
Ubuntu22.04

### ISSUE THREAD

**Issue by yu-mei** [mccdaq/daqhats#71]
Hi MCC support,

I am trying to use MCC 118 for my raspberry pi 4B with Ubunut 22.04 system. However, it does not work after installing it. The error is that 'cannot open the device'. 

I am glad if you could provide any guidances to fix this bug.

Thanks,

**Comment by nwright-mcc** [comment]
Ubuntu is not currently supported by the library, only Raspberry Pi OS.
